import { SessionProvider } from "next-auth/react"
import Head from 'next/head'
import '../styles/globals.css'

function MyApp({ Component, pageProps: { session, ...pageProps }, }) {
  return (
    <>
    <Head>
        <title>My Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionProvider session={session}>
        <Component {...pageProps} />
      </SessionProvider>
    </>
  )
}

export default MyApp
